<a href="https://colab.research.google.com/github/Jchang118/d2l/blob/main/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1.数据操作

1. 使用`arange`创建一个行向量`x`

In [1]:
import torch

## 2.1.1.入门

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

2. 通过张量的`shape`属性来访问张量(沿每个轴的长度)的形状

In [3]:
x.shape

torch.Size([12])

3. 通过张量的`numel`函数来检查它的大小(size)

In [4]:
x.numel()

12

4. 通过张量的`reshape`函数来改变其形状;我们也可以使用`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

5. 全0全1初始化矩阵

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

6. 通过某个特定的概率分布中随机采样来得到张量中每个元素的值,例如,创建一个形状为(3,4)的张量,其中的每个元素都从均值为0、标准差为1的标准高斯分布(正态分布)中随机采样

In [8]:
torch.randn(3, 4)

tensor([[ 1.0609, -0.4742,  0.4924, -0.5981],
        [-1.4498,  0.1518, -1.0485,  0.8930],
        [-0.5186,  1.1432, -0.0435, -0.6945]])

7. 通过提供包含数值的Python列表(或嵌套列表),来为所需张量中的每个元素赋予确定值

## 2.1.2.运算符

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

我们的兴趣不仅限于读取数据和写入数据.我们想在这些数据上执行数学运算,其中最简单且最有用的操作是按元素(elementwise)运算.对于任意具有相同形状的张量,**[常见的标准算术运算符(`+`、`-`、`*`、`/`和`**`)都可以被升级为按元素运算]**.我们可以在同一形状的任意两个张量上调用按元素操作.

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

(**“按元素”方式可以应用更多的计算**),包括像求幂这样的一元运算符.

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

除了按元素计算外,我们还可以执行线性代数运算,包括向量点积和矩阵乘法.我们将在`sec_linear-algebra`中解释线性代数的重点内容.

[**我们也可以把多个张量连结(concatenate)在一起**],把它们端对端地叠起来形成一个更大的张量.注意:`dim=0`沿行连结,`dim=1`沿列连结.

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

[**通过逻辑运算符构建二元张量**]

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

[**对张量中的所有元素进行求和,会产生一个单元素张量.**]

In [14]:
X.sum()

tensor(66.)

在上面的部分中,我们看到了如何在相同形状的两个张量上执行按元素操作.在某些情况下,[**即使形状不同我们然然可以通过调用*广播机制*(broardcasting mechanisim)来执行按元素操作**]. 这种机制的工作方式如下:
1. 通过适当复制元素来扩展一个或两个数组,以便在转换之后,两个张量具有相同的形状j;
2. 对生成的数组执行按元素操作.

在大多数情况下,我们将按着数组中长度为1的轴进行广播,如下例子:



## 2.1.3.广播机制

In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于`a`和`b`分别是3 x 1和1 x 2矩阵,如果让它们相加,它们的形状不匹配.我们将两个矩阵*广播*为一个更大的3 x 2矩阵:

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4.索引和切片

张量中的元素可以通过索引访问。与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1；可以指定范围以包含第一个元素和最后一个之前的元素。

In [17]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵。

In [18]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果我们想为多个元素赋相同的值，我们只需要索引所有元素，然后为它们赋值。

In [19]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5.节省内存

运行一些操作可能会导致为新结果分配内存。例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

在下面的例子中，我们用Python的id()函数演示了这一点，它给我们提供了内存中引用对象的确切地址。运行Y = Y + X后，我们会发现id()指向另一个位置。这是因为Python首先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置。

In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这可能是不可取的，原因有两个：
1. 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新；
2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

幸运的是，执行原地操作非常简单。我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>。为了说明这一点，我们首先创建一个新的矩阵Z，其形状与另一个Y相同，使用zeros_like来分配一个全0的块。

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 138442949500256
id(Z): 138442949500256


如果在后续计算中没有重复使用X，我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。

In [22]:
before = id(X)
X += Y
id(X) == before

True

## 2.1.6.转换为其他Python对象

将深度学习框架定义的张量转换为NumPy张量(ndarray)很容易，反之也同样容易。torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量。

In [23]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。

In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.7.小节

- 深度学习存储和操作数据的主要接口是张量(n维数组)。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。