<a href="https://colab.research.google.com/github/Jchang118/d2l/blob/main/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 数据操作

## 入门

1. 使用`arange`创建一个行向量`x`

In [2]:
import torch

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

2. 通过张量的`shape`属性来访问张量(沿每个轴的长度)的形状

In [ ]:
x.shape

torch.Size([12])

3. 通过张量的`numel`函数来检查它的大小(size)

In [ ]:
x.numel()

12

4. 通过张量的`reshape`函数来改变其形状;我们也可以使用`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`

In [ ]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

5. 全0全1初始化矩阵

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

6. 通过某个特定的概率分布中随机采样来得到张量中每个元素的值,例如,创建一个形状为(3,4)的张量,其中的每个元素都从均值为0、标准差为1的标准高斯分布(正态分布)中随机采样

In [8]:
torch.randn(3, 4)

tensor([[ 6.5486e-01,  6.0536e-01,  7.4836e-01,  5.2399e-02],
        [ 2.3199e-01, -9.8647e-01, -1.4142e+00, -1.0452e+00],
        [ 3.2041e-01, -1.6427e-04, -1.2988e-01,  3.9900e-01]])

7. 通过提供包含数值的Python列表(或嵌套列表),来为所需张量中的每个元素赋予确定值

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])